
/* ACCESS_PERIPH - A test peripheral with registers with different access permissions. */
#define TEST_ACCESS_PERIPH_BASE           0x40006000
#define TEST_ACCESS_PERIPH_RO_REG_OFFSET  0x0000
#define TEST_ACCESS_PERIPH_RO_REG         (TEST_ACCESS_PERIPH_BASE + TEST_ACCESS_PERIPH_RO_REG_OFFSET) /* read-only */
#define TEST_ACCESS_PERIPH_WO_REG_OFFSET  0x0004
#define TEST_ACCESS_PERIPH_WO_REG         (TEST_ACCESS_PERIPH_BASE + TEST_ACCESS_PERIPH_WO_REG_OFFSET) /* write-only */
#define TEST_ACCESS_PERIPH_RW_REG_OFFSET  0x0008
#define TEST_ACCESS_PERIPH_RW_REG         (TEST_ACCESS_PERIPH_BASE + TEST_ACCESS_PERIPH_RW_REG_OFFSET) /* read-write */
