
/* ARRAY_PERIPH - A test peripheral with a register array. */
#define TEST_ARRAY_PERIPH_BASE            0x40003000
#define TEST_ARRAY_PERIPH_CHANNEL0_OFFSET 0x0010
#define TEST_ARRAY_PERIPH_CHANNEL0        (TEST_ARRAY_PERIPH_BASE + TEST_ARRAY_PERIPH_CHANNEL0_OFFSET) /* read-write */
#define TEST_ARRAY_PERIPH_CHANNEL0_CONFIG (0xff << 0) /* 000000ff: Channel configuration */
#define TEST_ARRAY_PERIPH_CHANNEL0_CONFIG_MASK (0xff << 0)
#define TEST_ARRAY_PERIPH_CHANNEL1_OFFSET 0x0014
#define TEST_ARRAY_PERIPH_CHANNEL1        (TEST_ARRAY_PERIPH_BASE + TEST_ARRAY_PERIPH_CHANNEL1_OFFSET) /* read-write */
#define TEST_ARRAY_PERIPH_CHANNEL1_CONFIG (0xff << 0) /* 000000ff: Channel configuration */
#define TEST_ARRAY_PERIPH_CHANNEL1_CONFIG_MASK (0xff << 0)
#define TEST_ARRAY_PERIPH_CHANNEL2_OFFSET 0x0018
#define TEST_ARRAY_PERIPH_CHANNEL2        (TEST_ARRAY_PERIPH_BASE + TEST_ARRAY_PERIPH_CHANNEL2_OFFSET) /* read-write */
#define TEST_ARRAY_PERIPH_CHANNEL2_CONFIG (0xff << 0) /* 000000ff: Channel configuration */
#define TEST_ARRAY_PERIPH_CHANNEL2_CONFIG_MASK (0xff << 0)
#define TEST_ARRAY_PERIPH_CHANNEL3_OFFSET 0x001c
#define TEST_ARRAY_PERIPH_CHANNEL3        (TEST_ARRAY_PERIPH_BASE + TEST_ARRAY_PERIPH_CHANNEL3_OFFSET) /* read-write */
#define TEST_ARRAY_PERIPH_CHANNEL3_CONFIG (0xff << 0) /* 000000ff: Channel configuration */
#define TEST_ARRAY_PERIPH_CHANNEL3_CONFIG_MASK (0xff << 0)
