
/* CLUSTER_PERIPH - A test peripheral with a register cluster. */
#define TEST_CLUSTER_PERIPH_BASE          0x40004000
#define TEST_CLUSTER_PERIPH_TIMER0_CONTROL_OFFSET 0x0000
#define TEST_CLUSTER_PERIPH_TIMER0_CONTROL (TEST_CLUSTER_PERIPH_BASE + TEST_CLUSTER_PERIPH_TIMER0_CONTROL_OFFSET)
#define TEST_CLUSTER_PERIPH_TIMER0_DATA_OFFSET 0x0004
#define TEST_CLUSTER_PERIPH_TIMER0_DATA   (TEST_CLUSTER_PERIPH_BASE + TEST_CLUSTER_PERIPH_TIMER0_DATA_OFFSET)
#define TEST_CLUSTER_PERIPH_TIMER1_CONTROL_OFFSET 0x0010
#define TEST_CLUSTER_PERIPH_TIMER1_CONTROL (TEST_CLUSTER_PERIPH_BASE + TEST_CLUSTER_PERIPH_TIMER1_CONTROL_OFFSET)
#define TEST_CLUSTER_PERIPH_TIMER1_DATA_OFFSET 0x0014
#define TEST_CLUSTER_PERIPH_TIMER1_DATA   (TEST_CLUSTER_PERIPH_BASE + TEST_CLUSTER_PERIPH_TIMER1_DATA_OFFSET)
