
/* ENUM_PERIPH - A test peripheral with a register with enumerated values. */
#define TEST_ENUM_PERIPH_BASE             0x40005000
#define TEST_ENUM_PERIPH_CONFIG_OFFSET    0x0000
#define TEST_ENUM_PERIPH_CONFIG           (TEST_ENUM_PERIPH_BASE + TEST_ENUM_PERIPH_CONFIG_OFFSET)
#define TEST_ENUM_PERIPH_CONFIG_MODE      (0x3 << 0) /* 00000003: N/A */
#define TEST_ENUM_PERIPH_CONFIG_MODE_MASK (0x3 << 0)
#define TEST_ENUM_PERIPH_CONFIG_MODE_DISABLED 0
#define TEST_ENUM_PERIPH_CONFIG_MODE_ENABLED 1
